name: Deploy to GitLab Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitLab Pages
        env:
          GITLAB_REMOTE_URL: ${{ secrets.GITLAB_REMOTE_URL }} # e.g. https://<user>:${{ secrets.GITLAB_TOKEN }}@gitlab.com/<user>/<repo>.git
        run: |
          git remote add gitlab "${GITLAB_REMOTE_URL}"
          git subtree push --prefix public gitlab main 